# Site settings
title: "KlimovProject — Мой прожектор в WEB-разработках"
email: Klimov.RV@yandex.ru
description: "Первый официальный проект любого вебмастера - это его собственный сайт "
baseurl: ""
url: "/"
title_description: "Блог, как хороший пример статического сайта <br/> Здесь в свободной форме собраны мысли, 
идеи и заметки о моих разработках, а так же моё <a href=\"/portfolio/\">портфолио <i class=\"fas fa-hand-point-right\" aria-hidden=\"true\"></i></a>."
google_analytics: ""
disqus_account: 
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: KlimovRV
telegram_username: klimovrv
github_username:  klimov-rv
instagram_username: klimov.rv
reddit_username: 
linkedin_link: https://www.linkedin.com/in/%D1%80%D0%BE%D0%BC%D0%B0%D0%BD-%D0%BA%D0%BB%D0%B8%D0%BC%D0%BE%D0%B2-4598a9121/
google_plus_link: https://plus.google.com/113740816105565942618
stackoverflow_link: http://stackexchange.com/users/10611498/%d0%a0%d0%be%d0%bc%d0%b0%d0%bd-%d0%9a%d0%bb%d0%b8%d0%bc%d0%be%d0%b2
xing_link:
facebook_link: https://www.facebook.com/profile.php?id=100012300218634

# Footer
footer_left: "Сделано на <a href=\"https://jekyllrb.com/\">Jekyll</a> с <i class=\"fas fa-heart\"></i>"
footer_right: "&lt; <a href=\"https://github.com/klimov-rv/klimov-rv.github.io\">Github</a> &nbsp;<i class=\"fab fa-github-alt\"></i> /&gt;"

# Build settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

# KP settings
# permalink: /:year/:title:output_ext

# This will require each of these plugins automatically.
plugins: