# Site settings
title: "Klimov-Project"
email: site.projector@gmail.com
description: "Первый официальный проект любого вебмастера - это его собственный сайт "
baseurl: ""
url: "klimovproject.ru"
title_description: "Мой /dev блог, как хороший пример статического сайта <br/> 
на простом и быстром Jekyll. Здесь собраны мои мысли на разные темы, 
идеи и заметки о моих разработках, а так же могое другое.<br/>
Сборник ссылок на меня <i class=\"fa fa-arrow-circle-down\" aria-hidden=\"true\"></i>"
title_image: "/images/logo-klimov.jpg"
google_analytics: ""
disqus_account: 
github_repository: https://github.com/jacobtomlinson/
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: KlimovRV
github_username:  klimov-rv
instagram_username: klimov.rv
reddit_username: 
linkedin_link: https://www.linkedin.com/in/%D1%80%D0%BE%D0%BC%D0%B0%D0%BD-%D0%BA%D0%BB%D0%B8%D0%BC%D0%BE%D0%B2-4598a9121/
google_plus_link: https://plus.google.com/113740816105565942618
stackoverflow_link: http://stackexchange.com/users/10611498/%d0%a0%d0%be%d0%bc%d0%b0%d0%bd-%d0%9a%d0%bb%d0%b8%d0%bc%d0%be%d0%b2
xing_link:
facebook_link: https://www.facebook.com/profile.php?id=100012300218634

# Footer
footer_left: "Сделано с <i class=\"fa fa-heart\"></i> на <a href=\"https://jekyllrb.com/\">Jekyll</a>"
footer_right: "&lt; <a href=\"https://github.com/klimov-rv/klimov-rv.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i> /&gt;"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
